table transacoes
	lineageTag: cddb8633-6f09-43fd-9af7-1b4663bff02b

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: 2c4dde40-d392-4afb-935e-e691e5781142

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			```
		displayFolder: Medidas
		lineageTag: 011e2dcc-6366-4a0d-b8bf-ed0613714912

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		displayFolder: Medidas
		lineageTag: 61ca430b-e2ed-4bfd-8c6e-ebbfdd78a6df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		displayFolder: Colunas
		lineageTag: f3ed3195-4046-47dc-99e8-161257a6e5cd
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas
		lineageTag: 722044b0-7747-42e3-9f68-f724fc33ec17
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: df5db955-7c78-4891-9f08-194699d475d4
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 832592d1-3030-4f97-8f21-258724188e89
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    Fonte = SharePoint.Files("https://lirabr.sharepoint.com/sites/Projetos", [ApiVersion = 15]),
				    #"Colunas Reordenadas" = Table.ReorderColumns(Fonte,{"Content", "Name", "Extension", "Date accessed", "Date modified", "Folder Path", "Date created", "Attributes"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Reordenadas", each [Folder Path] = "https://lirabr.sharepoint.com/sites/Projetos/Shared Documents/Git/youtube-20241111-git-github-main/"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas1", each ([Name] = "transacoes.xlsx")),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas", "Conteudo", each Excel.Workbook([Content])),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Personalização Adicionada",{"Conteudo"}),
				    Conteudo = #"Outras Colunas Removidas"{0}[Conteudo],
				    transacoes_Table = Conteudo{[Item="transacoes",Kind="Table"]}[Data],
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

